###
GET http://localhost:3000/services HTTP/1.1

###
POST http://localhost:3000/services HTTP/1.1
Content-Type: application/json

{
  "name": "TesteName",
  "price": 3,
  "requiredTimeMin":2,
  "serviceImage": "TesteImage"
}
